[build]
  # Monorepo build command
  command = "pnpm install --ignore-scripts=false && pnpm generate:db && pnpm --filter @repo/db build && pnpm --filter @repo/user build"
  
  # Next.js output folder
  publish = "apps/user-app/.next"
  
  # Base of your monorepo
  base = "."

  [build.environment]
    NODE_VERSION = "18"
    NEXT_TELEMETRY_DISABLED = "1"
    NEXTAUTH_URL = "https://payments.mukeshtech.site"


[[plugins]]
  package = "@netlify/plugin-nextjs"

# Global security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Caching for static files
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Context-specific overrides (same command reused)
[context.production]
  command = "pnpm install --ignore-scripts=false && pnpm generate:db && pnpm --filter @repo/db build && pnpm --filter @repo/user build"

[context.deploy-preview]
  command = "pnpm install --ignore-scripts=false && pnpm generate:db && pnpm --filter @repo/db build && pnpm --filter @repo/user build"

[context.branch-deploy]
  command = "pnpm install --ignore-scripts=false && pnpm generate:db && pnpm --filter @repo/db build && pnpm --filter @repo/user build"
